import "./globals.css";
import localFont from "next/font/local";
import { Plus_Jakarta_Sans } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"], display: "swap" });
const calsans = localFont({
  src: "../../public/font/calsans.otf",
  variable: "--font-calsans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-blue-1 ${calsans.variable} ${jakarta.className}`} >{children}</body>
    </html>
  );
}
